
export const products = [
    { name: 'MICRONEEDLING', product: 'With Basic Serum (Hyaluronic Acid, Vitamin C, Vitamin Cocktail)', price: '£120' },
    { name: 'MICRONEEDLING', product: 'Add LED Light Therapy', price: '£25' },
    { name: 'MICRONEEDLING', product: 'Add Hyperboost Jelly Mask', price: '£15' },
    { name: 'MICRONEEDLING', product: 'With INFINI Premium Meso BTX', price: '£175', description: 'This is a soft lifting complex with hyaluronic acid and Argireline. A Tox without Toxin. An advanced cocktail to combat facial wrinkles and signs of skin ageing. A perfectly balanced combination of hyaluronic acid and argireline prevents the formation of new expressive wrinkles and reduces and stops the deepening of existing wrinkles, giving a spectacular smoothing effect. BTX is an effective stimulator of collagen and elastin synthesis and a stimulator of tissue restructuring. Its main action is muscle hydration of the skin, thanks to which the face regains its youthful contours and appears visibly smoother.' },
    { name: 'MICRONEEDLING', product: 'With INFINI Premium Meso Whitening Max', price: '£175', description: 'This is an innovative formula designed for skin depigmentation and whitening. Enables healthy glow restoration but also leaves it in perfect tone and condition. In order to obtain the desired effects, 4-8 sessions recommended every 10-14 days.' },
    { name: 'MICRONEEDLING', product: 'With Glutanex Glow', price: '£175', description: 'GLUTANEX GLOW is a professional solution for instant brightening, instant tone brightening, pore tightening, and skin regeneration. The combination of Glutathione and PDRN brings up the healthy glow from the inner layers of skin.'},
    {name: 'MICRONEEDLING', product: 'With Bella Dama Revital Lifting for Face and Neck', price: '£185'},
    {name: 'MICRONEEDLING', product: 'With Bella Dama BellaFace Plus Skin Rejuvenation', price: '£185'},
    // const masks = [
    { name: 'HYPERBOOST JELLY MASKS', product: 'Hyaluronic Acid', price: '£15', description: 'Hydrates, aids in retention of moisture, Reduces visible signs of ageing.' },
    { name: 'HYPERBOOST JELLY MASKS', product: 'Provence Lavender', price: '£15', description: 'Anti-Bacterial, antiseptic, reduces dark spots, lessens blotches and redness, soothing and calming, repairing, relieves irritation in dry skin.' },
    { name: 'HYPERBOOST JELLY MASKS', product: 'Fresh Mint', price: '£15', description: 'Contains Vitamin A (strengthens skin tissue), reduces sebum(oil) production), anti-pruritic (stops itching), antiseptic, relieves irritation, Thermoreceptor (cools the skin).' },
    { name: 'HYPERBOOST JELLY MASKS', product: 'Bulgarian Rose', price: '£15', description: 'Reduces wrinkles, healing hydrator, soothes redness, reduces sebum production, restores the skin’s PH levels, antiseptic.' },
    { name: 'HYPERBOOST JELLY MASKS', product: 'Milk Thistle and Pearl', price: '£15', description: 'Reduces damage from oxidising free radicals, anti-inflammatory, stimulates fibroblasts to accelerate healing in the skin, reduces the activation of Tyrosinase (an enzyme that causes the production of melanin) without this enzyme the skin appears more luminous.' },
    { name: 'HYPERBOOST JELLY MASKS', product: 'Bamboo Charcoal', price: '£15', description: 'Shrink pores and deeply cleanses. Draws bacteria, synthetic chemicals & dirt out from the skin’s surface, fights acne, improves skin’s texture, removes dead skin cells, protects damage to DNA due to its anti-oxidant & lipid barrier functions, protects epidermal tissues.' },
    { name: 'HYPERBOOST JELLY MASKS', product: 'Luxury 24K Gold', price: '£15', description: 'Anti-ageing, antioxidant, illuminates dull skin, brightens the complexion, tightens loose sagging skin, reduces wrinkles, improves skin texture, protects against damage, increases skin elasticity, reduces spots and blemishes.' },
    { name: 'HYPERBOOST JELLY MASKS', product: 'Tea Tree', price: '£15', description: 'Antiseptic, anti-inflammatory, soothes irritated skin, reduces redness and swelling, calms spots and boils, after-sun repair.' },
    { name: 'HYPERBOOST JELLY MASKS', product: 'Lemon', price: '£15', description: 'Evens out skin tone, astringent, anti-microbial, closes pores, lightens skin blemishes, evens out hyperpigmentation.' },
    { name: 'HYPERBOOST JELLY MASKS', product: 'Cherry', price: '£15', description: 'Reduces inflammation, tackles oxidative damage which leads to ageing, proven to soothe the skin, brightening.' },
    { name: 'HYPERBOOST JELLY MASKS', product: 'Kiwi', price: '£15', description: 'Controls excess sebum, combats free radicals, contains Vitamin E(aids regeneration of new skin cells), protects against UV damage, rich in Vitamin C & Amino acids, cools and soothes, cleanser, reduces dark circles under the eyes, brightening.' },
    { name: 'HYPERBOOST JELLY MASKS', product: 'CBD 1000MG', price: '£15', description: 'Treats mild skin irritation, reduces scar tissue and stretch marks, psoriasis, therapeutic agent for treatment of acne, sebostatic agent (regulates over production of sebum in the skin), calming.' },
    { name: 'HYPERBOOST JELLY MASKS', product: 'Vampire PLLA (POLY-L-LACTIC ACID) Infusion', price: '£15', description: 'Boosts the regeneration of collagen, gradually increases skin thickness for a smoother appearance, enhances facial volume and skin thickness that is lost with ageing.' },
    { name: 'HYPERBOOST JELLY MASKS', product: 'Belgium Cacao', price: '£15', description: 'Returns vigour to dry and aged skin, increases skin energy for a glowy appearance, smoothes skin leaving it radiant and velvety soft, promotes a younger looking and translucent complexion.' },
    { name: 'HYPERBOOST JELLY MASKS', product: 'Collagen', price: '£15', description: 'Reduces fine lines and wrinkles, stimulates skin cells, amplifies Collagen production, firming.' },


    // const peel = [
      { name: 'CHEMICAL PEEL', product: 'INFINI Premium BioAgePeel (First Session)', price: '£8', description: 'Innovative, medical chemical stimulator based on trichloroacetic, kojic and mandelic acid. Recommended 4 to 6 sessions 2 weeks apart' },
      { name: 'CHEMICAL PEEL', product: 'INFINI Premium BioAgePeel', price: '£45'},

    // const skinBoosters = [
    { name: 'SKIN BOOSTERS', type: 'FACE', product: 'PROFHILO H + L', price: '£280', description: 'Profhilo is an injectable anti-ageing treatment made from hyaluronic acid for skin that is losing its elasticity and firmness with age. It can be used on the face, neck, décolleté, arms, hands and knees, or any part of your body where the skin shows visible signs of ageing.' },
    { name: 'SKIN BOOSTERS', type: 'FACE', product: 'PROFHILO Haenkenium Antioxidant Cream 50 ml', price: '£50', description: 'This is so much more than just a moisturiser - this is a topical cream that provides immediate skin hydration, natural antioxidant protection and long term accumulative skin rejuvenation results.<br/>Combining a patented Hyaluronic Acid with Salvia Haenkei extract, this multitasking complex protects, restores and improves skin cell health within one skincare product.<br/>Recommended to use in conjunction with the Profhilo treatment for optimum and lasting results.' },
    { name: 'SKIN BOOSTERS', type: 'FACE', product: 'Revs PRO32', price: '£230', description: 'This is an incredible new 64mg skin booster 32mg high molecular weight HA and 32mg low molecular weight HA.<br/>INJECTION POINTS: 5 point injection each side of the face 0.2ml per injection point.<br/>Recommended minimum of 2 sessions booked 4 weeks apart then a top once a year (differs from one person to another based on age and skin’s needs).<br/>You can discuss the above with your therapist during your consultation.Discount available when purchased as a package, ask your therapist' },
    { name: 'SKIN BOOSTERS', type: 'FACE', product: 'Toskani TKN HA 3', price: '£250', description: 'Toskani TKN HA 3 is an injectable bio-revitaliser composed of 9mg/ml of non-cross linked hyaluronic acid. It has the highest molecular weight in the market (3.000 kDa), that is, the most similar to the skin physiological one. Having a larger molecule, its degradation is slower and its effects last longer providing a filler effect.<br/>Suitable for face, neck, décolleté and hands.' },
    { name: 'SKIN BOOSTERS', type: 'FACE', product: 'INFINI Premium Aquabooster', price: '£200', description: 'This is an innovative bio-revitalising skin booster which actively promotes revitalisation and rejuvenation.<br/>The uniqueness of the product lies in the use of uniquely stabilised hyaluronic acid chains, which not only ensures immediate rejuvenation an hydration of the skin, but also visible improvement in tension and density.<br/>Aquabooster restores natural volume and creates a smoothing effect by using high concentrations of soft cross-linked hyaluronic acid with a slow metabolic process.<br/>INFINI Aquabooster&apos;s unique formulation of high concentration hyaluronic acid ensures in-depth reconstruction of the skin structure and visible effects after just one treatment.' },
    { name: 'SKIN BOOSTERS', type: 'EYES', product: 'Dermaren Lumi Eyes', price: '£TBC', description: '' },
    { name: 'SKIN BOOSTERS', type: 'EYES', product: 'Ami Eyes', price: '£TBC', description: '' }
  ]

